// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeNumber2;

namespace PrimeNumber2.Migrations
{
    [DbContext(typeof(PrimeNumberContext))]
    [Migration("20201207221749_1_brandNew")]
    partial class _1_brandNew
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PrimeNumber2.Models.Number", b =>
                {
                    b.Property<Guid>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Guid")
                        .HasColumnName("Position");

                    b.Property<long>("IDN")
                        .HasColumnType("bigint")
                        .HasColumnName("IDN");

                    b.HasKey("Position");

                    b.ToTable("Numbers");
                });
#pragma warning restore 612, 618
        }
    }
}
