// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeNumber2;

namespace PrimeNumber2.Migrations
{
    [DbContext(typeof(PrimeNumberContext))]
    [Migration("20201211154757_2.0")]
    partial class _20
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PrimeNumber2.Models.PN2", b =>
                {
                    b.Property<long>("NTH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("NTH")
                        .UseIdentityColumn();

                    b.Property<long>("IDN")
                        .HasColumnType("bigint")
                        .HasColumnName("IDN");

                    b.HasKey("NTH");

                    b.ToTable("PrimeNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
